
  version: '3.8'
  
  services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5258:80"  # Map local port 5000 to container port 80
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Default=Server=localhost,1433;Database=BACKEND;User Id=sa;Password=reallyStrongPwd123;TrustServerCertificate=True;
        - Jwt__Issuer=BACKEND
        - Jwt__Audience=BACKEND
        - Jwt__Key=wECc8iL24rSMeHyI5QZRgJDMiOuEecdb2IHTiNjjmqg=
      volumes:
        - ./wwwroot/uploads:/app/wwwroot/uploads  # Persist uploads locally
      depends_on:
        - db
    
    db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=reallyStrongPwd123
      ports:
        - "1433:1433"
      volumes:
        - mssql-data:/var/opt/mssql
  
  volumes:
    mssql-data:
